
// Objective-C API for talking to the following Go packages
//
//	valera.co/vdk
//
// File is generated by gomobile bind. Do not edit.
#ifndef __VDK_FRAMEWORK_H__
#define __VDK_FRAMEWORK_H__

#include "VDK.objc.h"
#include "Universe.objc.h"

#endif
